### ISSUE TITLE
Require exact version or range for dependencies

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Cloud/repo-guidelines#1]
If the sample app is using a dependency manager (npm, pip, etc), the listed dependency version should either be exact or a finite range. Automated dependency updates using [Greenkeeper](http://greenkeeper.io/) should be allowed, as long as there are automated tests in place that ensure the application does not break due to a dependency update.

**Comment by jsloyer** [comment]
+1

**Comment by jsloyer** [comment]
That was supposed to be a +1
